Tweaked dockerfiles to work with non-privileged containers

diff --git a/backend/Dockerfile b/backend/Dockerfile
--- a/backend/Dockerfile
+++ b/backend/Dockerfile
@@ -1,21 +1,45 @@
 ARG BASE_IMAGE="node:14"
 FROM $BASE_IMAGE
 
-RUN apt-get update \
-    && apt-get install -y vim \
-    && apt-get install -y postgresql
+SHELL ["/bin/bash", "-c"]
 
-WORKDIR /usr/src/app
-COPY package.json /usr/src/app
+USER root
+RUN (type -P "yum" &> /dev/null) && ( \
+        yum install -y \
+            git \
+            vim \
+            postgresql
+        && yum clean all \
+        && rm -rf /var/cache/yum \
+     ) || ((type -P "apt-get" &> /dev/null) && ( \
+        apt-get update \
+        && apt-get install -y \
+            git \
+            vim \
+            postgresql
+        && apt-get clean \
+        && rm -rf /var/cache/apt/lists \
+    )) || ( \
+        >&2 echo "[ERROR] Unsupported Base Image" \
+        && exit 1 \
+    )
+USER node
+
+ENV APP_DIR="${HOME:-/home/node}"
+ENV APP_BIN="${APP_DIR}/node_modules/.bin"
+ENV PATH="${APP_BIN}:${PATH}"
+
+WORKDIR "${APP_DIR}"
+COPY package.json "${APP_DIR}"
 
 ARG NPM_REGISTRY="http://10.194.9.122"
-RUN npm install -g nodemon \
-    && npm install -g sequelize-cli \
-    && npm install -g jest \
+RUN npm install nodemon \
+    && npm install sequelize-cli \
+    && npm install jest \
     && npm config set registry "$NPM_REGISTRY" \
     && npm install
 
-COPY . /usr/src/app
+COPY . "${APP_DIR}"
 
 EXPOSE 8990
 CMD ./start.sh
